---
- hosts: web
  become: yes
  tasks:
  - name: update cache
    ansible.builtin.apt:
      cache_valid_time: 3600
      update_cache: true

  - name: Install apache2 latest version
    ansible.builtin.apt: 
      name: apache2 
      state: latest
  
  - name: Copy template
    ansible.builtin.template: 
      src: index.html.j2
      dest: /var/www/html/index.html
      mode: 0644
      owner: root
      group: root

- hosts: all
  become: yes
  tasks:
  - name: ensure ntpd is at the latest version
    ansible.builtin.apt: 
      name: ntp 
      state: latest
    notify:
    - restart ntpd


  handlers:
  - name: restart ntpd
    service: 
      name: ntpd 
      state: restarted
  
  - name: restart apache
    service: 
      name: apache2
      state: restarted

